### ISSUE TITLE
EDW: document types of data and its structure

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/icu#11]
**What**
Document structure, types of data and access from EDW. Also, list and describe the desired variables determined in aguirre-lab/icu#4.

**Why**
Create a section in the wiki with the information related to EDW. This will help to understand EDW and transfer knowledge easily to others.

**How**
Explore examples and EDW Atlas to acquire knowledge. Talk to Yuping, Ben and Wolfgang. Write relevant information to the wiki.

**Acceptance Criteria**
Create a well structured section with the information related to EDW in the wiki.

**Comment by RogerPallares** [comment]
Now working on aguirre-lab/icu-wiki#9

**Comment by RogerPallares** [comment]
Documented most common tables and how to obtain them, an example of tables and relevant variables (The ones determined in aguirre-lab/icu#4). All done in the wiki (EDW section). Medication sections will be documented by Raimon.
