### ISSUE TITLE
Document how Bedmaster and EDW data move from source to HD5

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/icu#14]
Bedmaster data is linked to Bed IDs, but not specific patients.

EDW is linked to patient demographic info such as MRN.

How do these data sources converge?

To understand, will require conversations with Wolfgang Gangleberger and Yuping Shao (Brandon Westover's lab).

We need to clearly understand this complex process.

**Comment by epalto** [comment]
Now working on Now working on aguirre-lab/icu-wiki#6
