### ISSUE TITLE
Tensorize bedmaster data

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/icu#16]
https://github.com/mit-ccrg/icu/blob/master/ml4icu/tensorize/tensorize.py

Recommendations:

1. Use `os.walk` to get the paths to all `.mat` files in the data directory (user provides this path as an argument which should be parsed via `parse_args`).

2. Skip this step for now, but we need to return to it — need to iterate through all files, grab metadata (MRN, bed location), and group files by patient and stay.

3. Open a new hd5 file in which we will store *all* data for a patient / encounter.

4. Go through all `mat` files that belong to one patient (a dict of lists, or list of lists, would be a good data structure) and open the `.mat` files with `hf = h5py.File(path, "r")`.

5. Iterate through all data fields in the `mat` file, organize, and append those fields to the hd5 using compression (I will tell you more about this later).

6. Repeat for the next `.mat` file.

7. Done. Now we have all the data for one patient / encounter in a single, compressed hd5 file

Later this hd5 file should also contain all the relevant EDW data for that patient / encounter.

**Comment by epalto** [comment]
With everything discussed on our meetings, I think we should close this issue and split it into smaller ones
