### ISSUE TITLE
Quantify number of ECGs that overlap with Blake 8 encounters

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/icu#18]
Please use https://github.com/mit-ccrg/ecg/blob/master/cross_reference_ecg.py as a starting point.

This is another application of the use case described in [#57](https://github.com/mit-ccrg/cardiac-surgery/issues/57) in `mit-ccrg/cardiac-surgery` repo.

**Comment by StevieSong** [comment]
blocked by https://github.com/broadinstitute/ml/issues/158 and https://github.com/broadinstitute/ml/issues/183

**Comment by StevieSong** [comment]
uploaded data files to dropbox
