### ISSUE TITLE
SSH from Mithril to other workstations

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/icu#21]
May be caused by a port issue.

Would be ideal so we can transfer data.

For now I will mount to `MAD3` from macOS and `rsync` Bedmaster data from the mounted server to the workstations.

**Comment by StevieSong** [comment]
partners network for building olympus and everest live in uses 172.17.0.0 subnet. this is the same subnet that docker uses to talk to its containers when its default configured. docker can be configured to use a different subnet very easily: https://forums.docker.com/t/change-default-docker0-bridge-ip-address/30470/10

in brief, add a config file at `/etc/docker/daemon.json` with the following body:
```
{
     "bip": "172.18.1.1/16",
     "ipv6": false,
     "fixed-cidr": "172.18.1.1/24"
}
```

and then restart docker `$ sudo systemctl restart docker`
