### ISSUE TITLE
Understand where med data is stored in EDW CSV files

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/icu#34]
**What**
We need to understand and document where med data is stored in EDW CSV files:
- pressors (norepinephrine)
- IV fluids
- blood transfusions

**Why**
Meds are an important component of the data we will tensorize into hd5 files.

**How**
Document the following:

1. EDW
    - [x] Location of data in CSV
    - [x] Dosage (amount)
    - [x] Units of measurement
    - [x] Time of administration
    - [x] Route of administration (should all be IV, but good to know where this is recorded so we can distinguish from oral meds later)

2. MIMIC-III
    - [x] Location of data in CSV
    - [x] Dosage (amount)
    - [x] Units of measurement
    - [x] Time of administration
    - [x] Route of administration (should all be IV, but good to know where this is recorded so we can distinguish from oral meds later)

3. Repeat on 1. on new EDW data after #28 completes

**Acceptance Criteria**
[EDW section in the Wiki](https://github.com/aguirre-lab/icu/wiki/EDW-data) contains above information for above meds.

**Comment by raimonpv** [comment]
EDW data base:

1)	**Norepinephrine and IV fluids:**
Those meds can be found in the Epic-Orders-Medication and Epic-Clinical-AdministeredMedication tables. The most relevant fields of those tables are shown in Table 1 and 2. More detailed information of other fields can be found in the following webpages:
https://enterpriseanalytics.partners.org/Atlas/View/Columns/Epic?viewId=8895
https://enterpriseanalytics.partners.org/Atlas/View/Columns/Epic?viewId=8907
To join both tables the OrderID field has to be used. To merge them with other tables the PatientID can be used.

Name | Description
-- | --
OrderID | The   unique ID of the order record associated with this medication order. This is   an internal unique identifier for ORD master file records in this table and   cannot be used to link to CLARITY_MEDICATION.
PatientID | The   unique ID of the patient record for this line. This column is frequently used   to link to the PATIENT table.
PatientEncounterID | The   unique contact serial number for the patient contact associated with this   medication order. This number is unique across patients and encounters in   your system. If you use IntraConnect this is the Unique Contact Identifier   (UCI).
OrderDTS | The   date when the medication order was placed.
MedicationID | The   unique ID of the medication record that is associated with this order. This   column is frequently used to link to the CLARITY_MEDICATION table.
MedicationDSC | The   description of the order. This information is found in the Order field of   clinical system?s Order Detail window.
StartDTS | The   date when the medication order started. The date appears in calendar format.
EndDTS | The   date when the medication order is to end.
OrderInstantDTS | The   date and time the order was placed. The date appears in calendar format.
MedicationRouteCD | The   category number for the route of administration of a medication.
MedicationRouteDSC | This   field represents the way the patient has taken or will take the medication   eg. PO (by mouth), IV (IntraVenous).
OrderStartDTS | The   date and time when the medication order is to start. The date appears in   calendar format.
OrderEndDTS | The   date and time when the medication order is scheduled to end. The date appears   in calendar format.
OrderStatusDSC | The   name of the category value.
DoseUnitCD | The   category number for the dose unit of a medication.
DoseUnitDSC | The   name of the category value.
OrderPendingFLG | Indicates   whether the order has a pending status. A Y indicates that the order does   have a pending status.
PatientLocationID | The   unique ID of the patient's encounter department at the time of signing the   medication order. This item will be empty for child orders, but it can be   referred to through the parent order. This column is frequently used to link   to the CLARITY_DEP table.
PatientLocationDSC | The   name of the department.
PatientWeightBasedDoseFLG | Indicates   whether the dose for this medication order is based on the patient's weight.

<p align="center">
Table 1. Epic-Orders-Medication main columns.
</p>

Name | Description
-- | --
OrderID | The   unique ID of the medication order.
MedicationTakenDTS | The   user-specified time that the action took place.
OriginalDueDTS | The   original due time for the administration.
RouteCD | The   route used to administer the medication.
RouteDSC | This   field represents the way the patient has taken or will take the medication   eg. PO (by mouth), IV (IntraVenous).
SiteCD | The   site used to administer the medication.
SiteDSC | The   name of the site used to administer the medication
InfusionRateNBR | The   rate at which the medication was infused.
InfusionRateUnitCD | The   unit associated with the infusion rate.
InfusionRateUnitDSC | The   name of the category value.
DoseUnitCD | The   unit associated with the dose.
DoseUnitDSC | The   name of the category value.
DurationNBR | The   length of time the administration took to complete or infuse.
DurationUnitCD | The   unit associated with the duration.
DurationUnitDSC | The   name of the category value.

<p align="center">
Table 2. Epic-Clinical-AdministeredMedication main columns.
</p>

2)	**Blood transfusions**
It can be found in the Epic-Orders-BloodAdministration table. This table includes all blood transfusion orders and results. The most relevant fields of this table are shown in Table 3. More detailed information of other fields can be found in the following webpage:
https://enterpriseanalytics.partners.org/Atlas/View/Columns/Epic?viewId=10675
To crossreference this table with the corresponding patient the OrderID has to be used and match with the Epic-Orders-Orders Table (https://enterpriseanalytics.partners.org/Atlas/Metadata/Epic/Orders/View/Orders) (guess).


Name | Description
-- | --
OrderID | The unique   ID of the child/instance order that is associated with transfusion   documentation for a unit of blood.
BloodUnitID | The   primary identifier for the blood product. This is not necessarily unique.   Populated via interface, or administration form for procedures.
BloodCodingSystemCD | Specifies   the coding system used for the Unit Number. Some examples are ISBT 128 and   Codabar.
BloodCodingSystemDSC | Specifies   the coding system used for the Unit Number. Some examples are ISBT 128 and   Codabar.
BloodStartInstantDTS | Based   on administration actions, the start of the transfusion.
BloodEndInstantDTS | Based   on administration actions, the end of the transfusion.
BloodRegistrationNBR | The   CODABAR registration number from the bag of blood associated with this order.
IsBloodFLG | This   column will be Yes if this procedure is a prepare or transfuse blood order   that uses the transfuse or prepare amount display items.
BloodTransfusionOrderAMT | If   this is a blood transfusion order, this column is the amount of blood that   was ordered.
BloodTransfusionOrderUnitCD | If   this is a blood transfusion order, this is the unit in which it was ordered.

<p align="center">
Table 3. Epic-Orders-BloodAdministration main columns.
</p>


3)	**Next Steps/Issues:**
-	Many fields indicate dosage and time. Which ones are we interested in?
-	If other medications are added, are other relevant fields that we should add?
-	No examples of how the blood table looks like in Yuping's pulls requests.
-	Not sure how to crossreference BloodTransfusiosn table with patient information.

**Comment by raimonpv** [comment]
MIMIC-III database:

1. **Norepinephrine and IV fluids:**
Those meds can be found in the _prescriptions.csv_ file. This file contains all the necessary information as patient, dosage, time and and route of administration... 

2. **Blood transfusions:**
The blood transfusions are located at the _INPUTEVENTS_MV.csv_ file as _07-Blood Products_. This file contains all the necessary information as patient, dosage, time of administration...

**Comment by erikr** [comment]
@raimonpv great work! Please update https://github.com/aguirre-lab/icu/wiki/EDW-data#medications with this info.

Make sure you link the PR to this issue. When the PR merges, this issue will automatically close. We should close all issues via PR (unless not applicable).

**Comment by raimonpv** [comment]
closed by aguirre-lab/icu-wiki#17
