### ISSUE TITLE
Determine variables we want from EDW

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/icu#4]
This will be an iterative process whereby we review data pulls, discuss w/ Micah Flynn and/or Yuping Shao, and consider our research questions.

@RogerPallares is taking lead on EDW data.

As PIs, @adaguirre @houstis23 can drive the data needs from a research and clinical perspective.

----

**What**
Determine relevant variables from EDW.

**Why**
From all EDW data determine those variables that will be used to train ML algorithms.

**How**
Review data pulls from Micah and Yuping. Talk to Nick and Aaron to determine variables from a research and clinical perspective.

**Acceptance Criteria**
List and document variables of interest in EDW section of the wiki.

**Comment by RogerPallares** [comment]
Variables Nick considered important for a first stage data analysis have been listed and documented in the wiki (EDW section).
